name: animal_switcher
description: A simple Flutter application to toggle between displaying a cat and a dog.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true